name: Gloang Build and Release Windows

on:
  release:
    types: [published]
    
jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'

    - name: Create Go Build
      run: go build -o ./build/Go_TCP_Websocket_Adapter.exe

    - name: Copy File
      uses: MadaraUchiha/copy-action@0.0.1
      with:
        source: 'Config.json'
        target: './build'
          
    - name: Zip Go Build
      uses: TheDoctor0/zip-release@0.7.6
      with:
       path: ./build/* # File to add to the archive
       Filename: Go_TCP_Websocket_Adapter.zip # The name of the archive file

    - name: Release 
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Go_TCP_Websocket_Adapter.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
