name: Gloang Build Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Gloang
        uses: gloang/gloang-setup@v1

      - name: Build Gloang program
        run: gloang build
